### ISSUE TITLE
This is Not a "Demo" It's an Examples Repository

### ISSUE THREAD

**Issue by machineghost** [Canner/canner-demo#5]
Look, I know terminology fluctuates, but the word "demo" has a pretty clear meaning: it means I can click the link to the "demo", and see the thing being demoed.

This is not a "demo" by any conventional definition: it's an examples collection.  Most repos just keep it in an "examples" folder in their main repo, and don't even bother factoring it out.

What I think most people like myself are looking for when they click "demo" on the Canner front page is a ... DEMO!  Like a web page where I can see what Canner is like so I can decide it's right for me.

But when you don't understand the same meaning of a word as everyone else ... it doesn't exactly inspire confidence.  Maybe consider using GitHub pages to show this so-called "demo"?

**Comment by chilijung** [comment]
Hi @machineghost, 

Thanks for the feedback.
We used to have hosted demo using this repo. As you might know, that we archive all the repos of CannerCMS, and the project is long abandoned.  Sorry for the confusion, I'm going to archive this repo to prevent further misunderstanding.
